name: Encounter World Religions Museum
markdown: redcarpet
pygments: true
permalink: none
traditions:
  christianity:
    name: Christianity
    slug: christianity
  hinduism:
    name: Hinduism
    slug: hinduism
